# Generated by Django 2.1.3 on 2018-11-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_task_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
