# Generated by Django 2.1.3 on 2018-11-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
