# Generated by Django 2.1.3 on 2018-11-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20181130_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Color'),
        ),
    ]
