# Generated by Django 2.1.3 on 2018-11-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_task_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='colors',
            new_name='color',
        ),
    ]
