# Generated by Django 2.1.3 on 2018-11-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20181130_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Color', verbose_name='Color'),
        ),
    ]
